# Generated by Django 3.2.8 on 2022-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='parking',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='sublet',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
