# Generated by Django 3.2.8 on 2022-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20220220_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateField(),
        ),
    ]
